# Generated by Django 4.0.4 on 2022-05-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='users/index.png', upload_to='users/profile_pic'),
        ),
    ]
