# Generated by Django 4.0.4 on 2022-05-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_post_downvote_alter_post_upvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('E', 'Event'), ('C', 'Charity')], max_length=1),
        ),
    ]
