# Generated by Django 4.0.4 on 2022-05-20 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_choice_questions_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='user',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
